# Generated by Django 5.2.3 on 2025-11-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified_user_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('contributor', 'Contributor'), ('researcher', 'Researcher'), ('expert', 'Expert')], default='contributor', max_length=20, null=True),
        ),
    ]
