# Generated by Django 5.2.3 on 2025-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('educator_researcher', 'Educator/Researcher'), ('policy_maker', 'Policy Maker'), ('tech_enthusiast', 'Tech Enthusiast'), ('climate_advocate', 'Climate Advocate'), ('nature_enthusiast', 'Nature Enthusiast'), ('media_personnel', 'Media Personnel')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contribution_method',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('enthusiast', 'Enthusiast'), ('expert', 'Expert')], max_length=20, null=True),
        ),
    ]
