# Generated by Django 5.2.3 on 2025-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_termsandconditions_usertermsacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='sections',
            field=models.JSONField(default=list, help_text='Structured sections for terms content'),
        ),
    ]
