# Generated by Django 4.2.11 on 2025-09-25 07:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biodiversity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('target_species', models.JSONField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('points_reward', models.IntegerField(default=100)),
                ('badge_reward', models.CharField(blank=True, max_length=255)),
                ('nft_reward', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('observations_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MissionParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observations_count', models.PositiveIntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='citizen.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['is_active'], name='citizen_mis_is_acti_65c4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['start_date'], name='citizen_mis_start_d_21b450_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['end_date'], name='citizen_mis_end_dat_b0fd8f_idx'),
        ),
        migrations.AddField(
            model_name='citizenobservation',
            name='biodiversity_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_observations', to='biodiversity.biodiversityrecord'),
        ),
        migrations.AddField(
            model_name='citizenobservation',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='citizen.mission'),
        ),
        migrations.AddField(
            model_name='citizenobservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='missionparticipation',
            unique_together={('user', 'mission')},
        ),
    ]
