# Generated by Django 4.2.11 on 2025-09-25 07:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodiversityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species_name', models.CharField(blank=True, max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='biodiversity/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='biodiversity/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='biodiversity/videos/')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('observation_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('ai_prediction', models.JSONField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=66)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodiversity_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observation_date'],
                'indexes': [models.Index(fields=['species_name'], name='biodiversit_species_162095_idx'), models.Index(fields=['observation_date'], name='biodiversit_observa_f01504_idx'), models.Index(fields=['contributor'], name='biodiversit_contrib_b1cd21_idx'), models.Index(fields=['is_verified'], name='biodiversit_is_veri_92ca74_idx'), models.Index(fields=['is_public'], name='biodiversit_is_publ_4250a0_idx')],
            },
        ),
    ]
