# Generated by Django 5.2.3 on 2025-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversityrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='biodiversity/images/'),
        ),
    ]
